#pragma once

#include <array>
#include <functional>
#include <memory>

#include <driver/gpio.h>
#include <esp_netif.h>

#include "base_component.hpp"
#include "ethernet.hpp"
#include "i2c.hpp"

namespace espp {
/// @brief Board Support Package (BSP) for the Waveshare ESP32-P4-WIFI6-POE-ETH board.
///
/// The ESP32-P4-WIFI6-POE-ETH pairs an ESP32-P4 (dual-core 360 MHz RISC-V,
/// 32 MB stacked PSRAM, 32 MB NOR flash) with an on-board ESP32-C6-MINI-1
/// (Wi-Fi 6 + Bluetooth 5 LE co-processor over SDIO) and a 10/100 RJ45
/// Ethernet port with a reserved header for a plug-in PoE power module.
///
/// This class provides a singleton interface to the board's peripherals:
/// - 10/100 Ethernet via the ESP32-P4 internal EMAC and an IP101GRI RMII PHY.
///   PoE is purely a power-supply feature (the RJ45 center taps feed bridge
///   rectifiers and a 5-pin header for Waveshare's PoE module, which produces
///   the board's 5 V rail) — no GPIO is involved, so a PoE-powered board looks
///   identical to a USB-powered one in software.
/// - The internal I2C bus (SDA=GPIO7, SCL=GPIO8), shared by the on-board
///   ES8311 audio codec (0x18) and the DSI/CSI connectors + 40-pin header.
///
/// Wi-Fi 6 / BLE are provided by the on-board ESP32-C6 over SDIO using
/// Espressif's ESP-Hosted + esp_wifi_remote components; espp does not (yet)
/// wrap that pattern in a BSP API, so this BSP documents the wiring (see the
/// pin constants below and the example README) instead of wrapping it:
///
/// <table>
/// <tr><th>Signal</th><th>ESP32-P4 GPIO</th><th>ESP32-C6 pin</th></tr>
/// <tr><td>SDIO CLK</td><td>18</td><td>IO19 (SDIO_CLK)</td></tr>
/// <tr><td>SDIO CMD</td><td>19</td><td>IO18 (SDIO_CMD)</td></tr>
/// <tr><td>SDIO D0</td><td>14</td><td>IO20 (SDIO_DATA0)</td></tr>
/// <tr><td>SDIO D1</td><td>15</td><td>IO21 (SDIO_DATA1)</td></tr>
/// <tr><td>SDIO D2</td><td>16</td><td>IO22 (SDIO_DATA2)</td></tr>
/// <tr><td>SDIO D3</td><td>17</td><td>IO23 (SDIO_DATA3)</td></tr>
/// <tr><td>C6 reset (CHIP_PU / EN)</td><td>54</td><td>EN</td></tr>
/// <tr><td>Spare cross-connect (0 Ω)</td><td>6</td><td>IO2</td></tr>
/// </table>
///
/// RMII pin mapping (ESP32-P4 routable EMAC pins; identical to the Waveshare
/// ESP32-P4-ETH / ESP32-P4-NANO). REF_CLK carries a 50 MHz reference clock
/// generated by the IP101GRI from its 25 MHz crystal:
///
/// <table>
/// <tr><th>Signal</th><th>GPIO</th></tr>
/// <tr><td>REF_CLK</td><td>50</td></tr>
/// <tr><td>TX_EN</td><td>49</td></tr>
/// <tr><td>TXD0</td><td>34</td></tr>
/// <tr><td>TXD1</td><td>35 (also the BOOT key / boot-strap pin, see below)</td></tr>
/// <tr><td>CRS_DV</td><td>28</td></tr>
/// <tr><td>RXD0</td><td>29</td></tr>
/// <tr><td>RXD1</td><td>30</td></tr>
/// <tr><td>MDC</td><td>31</td></tr>
/// <tr><td>MDIO</td><td>52</td></tr>
/// <tr><td>PHY_RST</td><td>51</td></tr>
/// </table>
///
/// Other on-board hardware not (yet) wrapped by this BSP (pin data from the
/// Waveshare schematic, see the component README):
/// - ES8311 audio codec + NS4150B amplifier + analog microphone
///   (I2S: MCLK=13, BCLK=12, WS/LRCK=10, DSDIN=9, ASDOUT=11; PA enable=53).
/// - microSD / TF slot on the fixed 4-bit SDMMC pins
///   (CLK=43, CMD=44, D0..D3=39/40/41/42; pull-ups powered from LDO_VO4).
/// - MIPI-DSI and MIPI-CSI 15-pin (Raspberry-Pi-style) connectors; panels and
///   cameras are sold separately (the Kit-C / Kit-D bundles include them).
/// - USB-A: native USB 2.0 OTG HS. USB-C: CH343P USB-UART console on
///   UART0 (TX=GPIO37, RX=GPIO38) with auto-reset/boot circuitry.
/// - The red LED next to the RJ45 is a 5 V power indicator, and the RJ45
///   green/yellow LEDs are driven by the PHY — none are GPIO-controllable.
///
/// \note The BOOT key (Key1) is wired to GPIO35, which per the schematic is
///       also the RMII TXD1 line to the IP101GRI. GPIO35 is the ESP32-P4's
///       boot-strap pin, sampled only at reset — once the EMAC is running the
///       pin is a TXD1 output, so the BOOT key cannot be used as a runtime
///       input. Like the other ESP32-P4 RMII BSPs (ESP32-P4-ETH /
///       ESP32-P4-NANO, identical pinout) this BSP therefore does not expose
///       a button API; the key is only useful for entering the serial
///       bootloader at reset.
///
/// \note Assumption pending hardware verification: PHY address 1 (PHY_AD0 is
///       strapped high through a 5.1 kΩ pull-up like the ESP32-P4-ETH).
///
/// The class is a singleton and can be accessed via get().
///
/// \section esp32_p4_wifi6_poe_eth_example Example
/// \subsection esp32_p4_wifi6_poe_eth_get_instance Get Instance
/// \snippet esp32_p4_wifi6_poe_eth_example.cpp esp32 p4 wifi6 poe eth get instance
/// \subsection esp32_p4_wifi6_poe_eth_dhcp_server DHCP Server
/// \snippet esp32_p4_wifi6_poe_eth_example.cpp esp32 p4 wifi6 poe eth dhcp server
/// \subsection esp32_p4_wifi6_poe_eth_dhcp_client DHCP Client
/// \snippet esp32_p4_wifi6_poe_eth_example.cpp esp32 p4 wifi6 poe eth dhcp client
class Esp32P4Wifi6PoeEth : public BaseComponent {
public:
  /// Callback invoked (SERVER mode only) each time the DHCP server assigns an
  /// IP address to a connected client.
  using client_ip_callback_t = std::function<void(esp_ip4_addr_t ip, std::array<uint8_t, 6> mac)>;

  /// Callback invoked when the Ethernet link state changes (comes up or goes
  /// down) or when the IP address is lost.
  /// \note Runs in the ESP-IDF event-loop task context — return quickly, do not block.
  using EthernetLinkCallback = std::function<void()>;

  /// Callback invoked when the interface obtains an IPv4 address.
  /// \param ip The assigned IPv4 address.
  /// \note Runs in the ESP-IDF event-loop task context — return quickly, do not block.
  using EthernetIpCallback = std::function<void(esp_ip4_addr_t ip)>;

  /// DHCP operating mode for the Ethernet interface
  enum class DhcpMode {
    CLIENT, ///< DHCP client — acquire an IP from an upstream server (default)
    SERVER, ///< DHCP server — assign IPs to hosts connected to this interface
  };

  /// Static IP configuration used when operating as a DHCP server.
  /// Leave \c ip_info zero-initialised to use the built-in defaults
  /// (192.168.4.1 / 255.255.255.0 / gw 192.168.4.1).
  struct ServerConfig {
    esp_netif_ip_info_t ip_info{};                    ///< zero-initialised → 192.168.4.1/24
    client_ip_callback_t on_client_assigned{nullptr}; ///< Called for each assigned client IP.
  };

  /// Configuration for the Ethernet interface.
  struct EthernetConfig {
    DhcpMode mode{DhcpMode::CLIENT};            ///< DHCP operating mode.
    ServerConfig server_config{};               ///< Only used when mode == SERVER.
    EthernetLinkCallback on_link_up{nullptr};   ///< Physical link came up.
    EthernetLinkCallback on_link_down{nullptr}; ///< Physical link went down.
    EthernetIpCallback on_got_ip{nullptr};      ///< Interface obtained an IPv4 address.
    EthernetLinkCallback on_lost_ip{nullptr};   ///< Interface lost its IPv4 address.
  };

  /// @brief Access the singleton instance
  /// @return Reference to the singleton instance
  static Esp32P4Wifi6PoeEth &get() {
    static Esp32P4Wifi6PoeEth instance;
    return instance;
  }

  Esp32P4Wifi6PoeEth(const Esp32P4Wifi6PoeEth &) = delete;
  Esp32P4Wifi6PoeEth &operator=(const Esp32P4Wifi6PoeEth &) = delete;
  Esp32P4Wifi6PoeEth(Esp32P4Wifi6PoeEth &&) = delete;
  Esp32P4Wifi6PoeEth &operator=(Esp32P4Wifi6PoeEth &&) = delete;

  /// Get a reference to the internal I2C bus (SDA=GPIO7, SCL=GPIO8)
  /// \return A reference to the internal I2C bus
  /// \note Shared by the on-board ES8311 audio codec (0x18) and the DSI / CSI
  ///       connectors and 40-pin header
  I2c &internal_i2c() { return internal_i2c_; }

  /////////////////////////////////////////////////////////////////////////////
  // Ethernet (EMAC + IP101GRI RMII PHY)
  /////////////////////////////////////////////////////////////////////////////

  /// Initialize the Ethernet interface (EMAC + IP101GRI RMII PHY).
  /// \param config  Ethernet configuration (DHCP mode, callbacks).
  ///                All fields have defaults so \c EthernetConfig{} gives a
  ///                plain DHCP-client interface with no callbacks.
  /// \return True if Ethernet was successfully initialized and started. False
  ///         on failure, or if Ethernet was already initialized -- in that
  ///         case the provided \p config is ignored (reinitialization with a
  ///         new configuration is not supported).
  /// \note Requires the ESP-IDF TCP/IP stack and default event loop. The
  ///       underlying espp::Ethernet component calls esp_netif_init() and
  ///       esp_event_loop_create_default() during its initialize(), so they
  ///       are created here if the application has not already done so.
  bool initialize_ethernet(const EthernetConfig &config);

  /// Initialize Ethernet with default configuration (DHCP client mode).
  /// \return True if Ethernet was successfully initialized and started. False
  ///         on failure or if Ethernet was already initialized.
  bool initialize_ethernet();

  /// Check whether the interface has a usable IP address
  /// (DHCP lease granted in CLIENT mode, or link is up in SERVER mode).
  /// \return True if the interface is connected with a valid IP.
  bool is_ethernet_connected() const { return ethernet_ && ethernet_->is_connected(); }

  /// Get the most recently acquired IPv4 address (0 if none).
  /// \return The IPv4 address.
  esp_ip4_addr_t ethernet_ip() const { return ethernet_ ? ethernet_->ip() : esp_ip4_addr_t{}; }

  /////////////////////////////////////////////////////////////////////////////
  // ESP32-C6 (Wi-Fi 6 / BLE co-processor, ESP-Hosted over SDIO)
  /////////////////////////////////////////////////////////////////////////////
  // These constants document the ESP32-P4 <-> ESP32-C6 wiring for configuring
  // Espressif's esp_hosted component (see the example README). The BSP does
  // not bring up the C6 itself.
  static constexpr int c6_sdio_clk_io = 18; ///< P4 SDIO CLK -> C6 IO19 (SDIO_CLK)
  static constexpr int c6_sdio_cmd_io = 19; ///< P4 SDIO CMD -> C6 IO18 (SDIO_CMD)
  static constexpr int c6_sdio_d0_io = 14;  ///< P4 SDIO D0  -> C6 IO20 (SDIO_DATA0)
  static constexpr int c6_sdio_d1_io = 15;  ///< P4 SDIO D1  -> C6 IO21 (SDIO_DATA1)
  static constexpr int c6_sdio_d2_io = 16;  ///< P4 SDIO D2  -> C6 IO22 (SDIO_DATA2)
  static constexpr int c6_sdio_d3_io = 17;  ///< P4 SDIO D3  -> C6 IO23 (SDIO_DATA3)
  static constexpr int c6_reset_io = 54;    ///< P4 GPIO54 -> C6 EN (CHIP_PU) via 0 Ω
  static constexpr int c6_spare_io = 6;     ///< P4 GPIO6 -> C6 IO2 via 0 Ω (unused spare)

protected:
  Esp32P4Wifi6PoeEth();

  /////////////////////////////////////////////////////////////////////////////
  // RMII / EMAC pin constants (IP101GRI PHY)
  /////////////////////////////////////////////////////////////////////////////
  static constexpr int eth_mdc_io = 31;
  static constexpr int eth_mdio_io = 52;
  static constexpr int eth_ref_clk_io = 50;
  static constexpr int eth_phy_reset_gpio = 51;
  static constexpr int eth_phy_addr = 1;
  static constexpr int eth_tx_en_io = 49;
  static constexpr int eth_txd0_io = 34;
  // NOTE: GPIO35 is shared with the BOOT key (P4 boot-strap pin, sampled only
  //       at reset) — it is exclusively the EMAC TXD1 output at runtime.
  static constexpr int eth_txd1_io = 35;
  static constexpr int eth_crs_dv_io = 28;
  static constexpr int eth_rxd0_io = 29;
  static constexpr int eth_rxd1_io = 30;

  /////////////////////////////////////////////////////////////////////////////
  // Internal I2C bus (ES8311 codec 0x18; DSI / CSI connectors; 40-pin header)
  /////////////////////////////////////////////////////////////////////////////
  static constexpr auto internal_i2c_port = I2C_NUM_0;
  static constexpr auto internal_i2c_clock_speed = 400 * 1000;
  static constexpr gpio_num_t internal_i2c_sda = GPIO_NUM_7;
  static constexpr gpio_num_t internal_i2c_scl = GPIO_NUM_8;

  /////////////////////////////////////////////////////////////////////////////
  // Member variables
  /////////////////////////////////////////////////////////////////////////////

  // The board's RMII Ethernet is driven by the reusable espp::Ethernet component
  // (this BSP just supplies the board-specific pins / PHY).
  std::unique_ptr<espp::Ethernet> ethernet_;

  // Internal I2C bus
  I2c internal_i2c_{{.port = internal_i2c_port,
                     .sda_io_num = internal_i2c_sda,
                     .scl_io_num = internal_i2c_scl,
                     .sda_pullup_en = GPIO_PULLUP_ENABLE,
                     .scl_pullup_en = GPIO_PULLUP_ENABLE,
                     .clk_speed = internal_i2c_clock_speed}};
}; // class Esp32P4Wifi6PoeEth
} // namespace espp
