// Host-buildable unit tests for the runtime report map / decoders
// (hid-rp-report-map.hpp). Build & run:
//
//   c++ -std=c++20 -Wall -Wextra -Werror \
//       -isystem components/hid-rp/include \
//       -isystem components/hid-rp/detail/hid-rp/hid-rp \
//       -isystem components/format/include \
//       -isystem components/format/detail/fmt/include \
//       components/hid-rp/test/hid_rp_report_map_host_test.cpp -o
//       /tmp/hid_rp_report_map_host_test \
//       && /tmp/hid_rp_report_map_host_test
//
// No ESP-IDF headers required.

#include <cstdint>
#include <cstdio>
#include <vector>

#include "hid-rp-gamepad.hpp"
#include "hid-rp-report-map.hpp"

static int failures = 0;
#define CHECK(cond)                                                                                \
  do {                                                                                             \
    if (!(cond)) {                                                                                 \
      std::printf("FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond);                                  \
      failures++;                                                                                  \
    }                                                                                              \
  } while (0)

// A descriptor generated by hid-rp's gamepad report (the same one an espp
// BLE/USB gamepad advertises): 16 buttons, two sticks, two triggers, a hat.
static void test_generated_gamepad() {
  using Gamepad = espp::GamepadInputReport<16>;
  // get_descriptor() is the collection body; a device wraps it in the
  // application collection (as the hid-rp-gamepad docs show)
  using namespace hid::page;
  using namespace hid::rdf;
  auto rdf_descriptor = descriptor(usage_page<generic_desktop>(), usage(generic_desktop::GAMEPAD),
                                   collection::application(Gamepad::get_descriptor()));
  std::vector<uint8_t> desc(rdf_descriptor.begin(), rdf_descriptor.end());

  auto map = espp::hid_rp::ReportMap::parse(desc);
  CHECK(map.has_value());
  if (!map)
    return;
  size_t buttons = 0, axes = 0, hats = 0;
  for (const auto &f : map->fields()) {
    if (f.usage_page == espp::hid_rp::usage::PAGE_BUTTON)
      buttons++;
    if (f.usage_page == espp::hid_rp::usage::PAGE_GENERIC_DESKTOP &&
        f.usage >= espp::hid_rp::usage::GD_X && f.usage <= espp::hid_rp::usage::GD_RZ)
      axes++;
    if (f.usage_page == espp::hid_rp::usage::PAGE_GENERIC_DESKTOP &&
        f.usage == espp::hid_rp::usage::GD_HAT)
      hats++;
  }
  CHECK(buttons == 16);
  CHECK(axes >= 4);
  CHECK(hats == 1);

  // Build a report with the generator, decode it with the mapper.
  Gamepad report;
  report.reset();
  report.set_button(2, true);  // Xbox-style: 2 = east
  report.set_button(10, true); // start
  report.set_hat(espp::gamepad::Hat::UP);
  report.set_left_joystick(-1.0f, 0.0f);
  report.set_right_joystick(0.0f, 1.0f);
  auto bytes = report.get_report();
  std::vector<uint8_t> raw(bytes.begin(), bytes.end());
  if (map->uses_report_ids()) {
    raw.insert(raw.begin(), Gamepad::ID);
  }

  espp::hid_rp::GamepadDecoder decoder(*map);
  CHECK(decoder.looks_like_gamepad());
  // a hat plus 16 buttons reads as a DualShock-style pad to the heuristic;
  // pin the layout the assertions below assume
  CHECK(decoder.quirks().layout == espp::hid_rp::GamepadDecoder::Layout::DirectInput);
  decoder.quirks().layout = espp::hid_rp::GamepadDecoder::Layout::Xbox;
  espp::hid_rp::GamepadReport g;
  CHECK(decoder.decode(raw, g));
  CHECK(g.east);
  CHECK(!g.south && !g.west && !g.north);
  CHECK(g.start);
  CHECK(g.up && !g.down);
  CHECK(g.lx < -30000);
  CHECK(g.left); // full left stick deflection also reads as d-pad left
  CHECK(g.ry > 30000);
}

// The classic boot-protocol keyboard descriptor (8-byte reports: modifier
// bitmap, reserved byte, six key usages), then an NKRO-style bitmap.
static void test_keyboard() {
  static const uint8_t desc[] = {
      0x05, 0x01, 0x09, 0x06, 0xA1, 0x01, // Generic Desktop, Keyboard, Application collection
      0x05, 0x07, 0x19, 0xE0, 0x29, 0xE7, 0x15, 0x00, 0x25, 0x01,
      0x75, 0x01, 0x95, 0x08, 0x81, 0x02,                         // 8 modifier bits (variable)
      0x95, 0x01, 0x75, 0x08, 0x81, 0x01,                         // reserved byte (constant)
      0x95, 0x06, 0x75, 0x08, 0x15, 0x00, 0x25, 0x65, 0x05, 0x07, // 6 key slots (array)
      0x19, 0x00, 0x29, 0x65, 0x81, 0x00, 0xC0};
  auto map = espp::hid_rp::ReportMap::parse(desc);
  CHECK(map.has_value());
  if (!map)
    return;
  CHECK(!map->uses_report_ids());
  CHECK(map->report_bytes(0) == 8);
  espp::hid_rp::KeyboardDecoder kb(*map);
  CHECK(kb.looks_like_keyboard());
  const uint8_t report[8] = {0x02, 0, 0x04, 0x52, 0, 0, 0, 0}; // left shift, 'a', up arrow
  espp::hid_rp::KeyboardReport k;
  CHECK(kb.decode(report, k));
  CHECK(k.pressed(0xE1));
  CHECK(k.pressed(0x04));
  CHECK(k.pressed(0x52));
  CHECK(!k.pressed(0xE0));
  CHECK(!k.pressed(0x05));
}

// A boot-protocol mouse: 3 buttons, relative X / Y (signed bytes), wheel.
static void test_mouse() {
  static const uint8_t desc[] = {
      0x05, 0x01, 0x09, 0x02, 0xA1, 0x01, 0x09, 0x01, 0xA1, 0x00, // Mouse / Pointer
      0x05, 0x09, 0x19, 0x01, 0x29, 0x03, 0x15, 0x00, 0x25, 0x01, 0x95, 0x03,
      0x75, 0x01, 0x81, 0x02,                                                 // 3 buttons
      0x95, 0x01, 0x75, 0x05, 0x81, 0x01,                                     // padding
      0x05, 0x01, 0x09, 0x30, 0x09, 0x31, 0x09, 0x38, 0x15, 0x81, 0x25, 0x7F, // X Y Wheel
      0x75, 0x08, 0x95, 0x03, 0x81, 0x06,                                     // relative
      0xC0, 0xC0};
  auto map = espp::hid_rp::ReportMap::parse(desc);
  CHECK(map.has_value());
  if (!map)
    return;
  espp::hid_rp::MouseDecoder mouse(*map);
  CHECK(mouse.looks_like_mouse());
  const uint8_t report[4] = {0x01, static_cast<uint8_t>(-5), 0x03, static_cast<uint8_t>(-1)};
  espp::hid_rp::MouseReport m;
  CHECK(mouse.decode(report, m));
  CHECK(m.buttons == 0x01);
  CHECK(m.dx == -5);
  CHECK(m.dy == 3);
  CHECK(m.wheel == -1);
}

// Report IDs, a Consumer-page array item, and DPad usages (the Xbox-style
// layout many mobile controllers use).
static void test_report_ids_consumer_dpad() {
  static const uint8_t desc[] = {
      0x05, 0x01, 0x09, 0x05, 0xA1, 0x01, // Gamepad
      0x85, 0x01,                         // report ID 1
      0x05, 0x09, 0x19, 0x01, 0x29, 0x0C, 0x15, 0x00, 0x25, 0x01,
      0x75, 0x01, 0x95, 0x0C, 0x81, 0x02,                         // 12 buttons
      0x95, 0x04, 0x81, 0x01,                                     // 4 bits padding
      0x05, 0x01, 0x19, 0x90, 0x29, 0x93, 0x95, 0x04, 0x81, 0x02, // DPad up/down/right/left
      0x95, 0x04, 0x81, 0x01,                                     // padding
      0x05, 0x0C, 0x15, 0x00, 0x26, 0xFF, 0x03, 0x19, 0x00, 0x2A,
      0xFF, 0x03, 0x75, 0x10, 0x95, 0x01, 0x81, 0x00, // consumer control (array, 16-bit)
      0xC0};
  auto map = espp::hid_rp::ReportMap::parse(desc);
  CHECK(map.has_value());
  if (!map)
    return;
  CHECK(map->uses_report_ids());
  CHECK(map->report_bytes(1) == 5);
  espp::hid_rp::GamepadDecoder decoder(*map);
  CHECK(decoder.quirks().layout == espp::hid_rp::GamepadDecoder::Layout::Xbox);
  // ID 1, button 1 (south) + button 6 (R1), DPad right, consumer AC Back
  const uint8_t report[6] = {0x01, 0x21, 0x00, 0x04, 0x24, 0x02};
  espp::hid_rp::GamepadReport g;
  CHECK(decoder.decode(report, g));
  CHECK(g.south);
  CHECK(g.r1);
  CHECK(g.right && !g.left);
  CHECK(g.select); // AC Back
  CHECK(g.consumer[0] == 0x0224);
  // a report with another ID carries none of these fields
  const uint8_t other[6] = {0x02, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
  CHECK(!decoder.decode(other, g));
}

int main() {
  test_generated_gamepad();
  test_keyboard();
  test_mouse();
  test_report_ids_consumer_dpad();
  if (failures == 0) {
    std::printf("hid_rp_report_map_host_test: all checks passed\n");
    return 0;
  }
  std::printf("hid_rp_report_map_host_test: %d failure(s)\n", failures);
  return 1;
}
