idf_component_register(
  INCLUDE_DIRS "include"
  SRC_DIRS "src"
  REQUIRES
    "base_component"
    "ethernet"
    "esp_netif"
    "fatfs"
    "esp_driver_sdmmc"
    "sdmmc"
    "codec"
    "i2c"
    "task"
    "esp_driver_i2s"
    "display"
    "display_drivers"
    "gt911"
    "input_drivers"
    "interrupt"
    "esp_lcd"
    "esp_video"
    "esp_cam_sensor"
  REQUIRED_IDF_TARGETS "esp32p4"
  )
