name: Build and Publish Documentation (Pushes)

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: 'pip'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz texlive-full pandoc
          pip install -r doc/requirements.txt

      - name: Build Documentation (HTML)
        run: |
          cd doc
          # ignore if the following command fails
          build-docs -bs html -t esp32 -l en --project-path ../ --source-dir ./ --doxyfile_dir ./ || true
          # copy the generated HTML files to the docs directory for GitHub Pages
          mkdir -p ../docs
          cp -r _build/en/esp32/html/* ../docs/.

      - name: Build Documentation (PDF)
        run: |
          cd doc
          if sh ./build_latex_pdf.sh _build/en/esp32/latex; then
            echo "PDF_GENERATED=true" >> $GITHUB_ENV
          else
            rm -f _build/en/esp32/latex/refman.pdf
            rm -f _build/en/esp32/latex/espp_documentation.pdf
            echo "PDF_GENERATED=false" >> $GITHUB_ENV
          fi
          # warn if the PDF was not generated successfully
          if [ "$PDF_GENERATED" = "false" ]; then
            echo "Warning: PDF documentation was not generated successfully."
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true

      - uses: actions/upload-artifact@v4
        if: env.PDF_GENERATED == 'true'
        with:
          name: espp_documentation.pdf
          path: doc/_build/en/esp32/latex/espp_documentation.pdf

      - name: Attach files to release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event.release && github.event.action == 'published' && env.PDF_GENERATED == 'true' }}
        with:
          files: |
            doc/_build/en/esp32/latex/espp_documentation.pdf
