name: Build Host C++ / Python Libraries

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_windows:

    runs-on: windows-latest
    continue-on-error: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build libraries
      working-directory: lib/
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release --target install

    - name: Upload output folder
      uses: actions/upload-artifact@v4
      with:
        name: libespp_windows
        path: lib/pc

  build_linux:

    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build libraries
      working-directory: lib/
      run: |
        ./build.sh

    - name: Upload output folder
      uses: actions/upload-artifact@v4
      with:
        name: libespp_linux
        path: lib/pc

  build_macos:

    runs-on: macos-latest
    continue-on-error: false

    steps:
    - name: Setup XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Build libraries
      working-directory: lib/
      run: |
        ./build.sh

    - name: Upload output folder
      uses: actions/upload-artifact@v4
      with:
        name: libespp_macos
        path: lib/pc
